[package]
edition = "2018"
name = "star-utils"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-derive = "1"

[dependencies.napi]
version = "1"
features = ["napi8"]

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
